# Generated by Django 3.1 on 2020-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reci', models.CharField(max_length=500)),
                ('cookingOrder', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
